use_frameworks!

platform :ios, '9.0'
pod 'FullStory', :http => 'https://ios-releases.fullstory.com/fullstory-1.3.0.tar.gz'
pod 'Analytics', '~> 3.0'

target 'FullStorySegmentMiddleware_Example' do
  pod 'FullStorySegmentMiddleware', :path => '../'
  pod 'OCMock', '~>3.6'

  target 'FullStorySegmentMiddleware_Tests' do
    inherit! :search_paths
    
  end
end
