use_frameworks!

platform :ios, '8.0'

target 'FullStorySegmentMiddleware_Example' do
  pod 'FullStorySegmentMiddleware', :path => '../'

  target 'FullStorySegmentMiddleware_Tests' do
    inherit! :search_paths

    
  end
end
